"use strict";


let data = [
    {
id:1,
first:"Volva",

description:["Country of origin",
"Production years",
"Series",
],
block:["sweden",
"1937",
"48",
],
firstly:"https://s.car.info/image_files/logos/180/1094.jpg",
secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",


fon:["Clasifieds",
"volva",
"30,234",
"statistics",
"volva",
"12,300",
"map",
"volva",
"1,233,500",
"images",
"volva",
"123,956",
],
done:"Series",
foto:["https://s.car.info/image_files/360/front-side-1-1057214.jpg",
"https://s.car.info/image_files/180/1364735.jpg",
"https://s.car.info/image_files/180/1276698.jpg",
"https://s.car.info/image_files/360/front-side-1-1409981.jpg",
],

page:["EM90",
"MPV 6 seats",
"Electric",
"EM30",
"SUV 5 seats",
"Electric",
"EX90",
"SUV 7 seats",
"Electric",
"S60",
"Sedan 5 seats",
"Petrol Diesel",
],
secret:["2021",
"em 34",
"123,000dollars",
"dc",
"2022",
"45,000dollars",
"suv500",
"vol207",
"2023",
"20dw",
"suv23",
"76,000euro",
"2024",
"lux23",
"340,000dollars",
"dc39",
],
text:"",
images:"https://s.car.info/image_files/logos/90/1094.jpg",

title:"Volvo",
micro:"1927-",
imgs:"https://s.car.info/g/flags/svg/mini/se.svg",
    },
    {
        id:2,
        first:"volkswagen",

description:["Country of origin",
"Production years",
"Series",
],
block:["germany",
"1937",
"207",
],
firstly:"https://s.car.info/image_files/logos/90/1093.jpg",
secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
fon:["Clasifieds",
"volkswagen",
"30,234",
"statistics",
"volkswagen",
"12,300",
"map",
"volkswagen",
"1,233,500",
"images",
"volkswagen",
"123,956",
],
        done:"Series",
     foto:["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS71G8fUDv1X5yvcLDGtucmM5jUCSx7rlf6flH6_Jtk9g&s",
     "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRchPan2PF4OoRsHH-BEuJwd6tmOWws6IfpDsOg70gHzg&s",
     "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7HJCO8rH2H6xgcRQyD_PDgHye8_KCp4X7y337nOi3v95FSspLBTZ0rwKhhLa3d5ESguc&usqp=CAU",
     "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxGf1Vbkqokf-CEN8vtJs6NzansNWoV49YIv8ItijTrwoS-zaJ-kQmvD0t774hq6y9ZmQ&usqp=CAU",
     ],
     page:["EM90",
     "MPV 6 seats",
     "Electric",
     "EM30",
     "SUV 5 seats",
     "Electric",
     "EX90",
     "SUV 7 seats",
     "Electric",
     "S60",
     "Sedan 5 seats",
     "Petrol Diesel",
     ],
     secret:["2021",
     "em 34",
     "123,000dollars",
     "dc",
     "2022",
     "45,000dollars",
     "suv500",
     "vol207",
     "2023",
     "20dw",
     "suv23",
     "76,000euro",
     "2024",
     "lux23",
     "340,000dollars",
     "dc39",
     ],

images:"https://s.car.info/image_files/logos/90/1093.jpg",
title:"Volkswagen",
micro:"1938-",
imgs:"https://s.car.info/g/flags/svg/mini/de.svg",
    },
    {
        id:3,
        first:"TOYOTA",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["japan",
        "1936",
        "land cruicer 200",
        ],
        fistly:"https://s.car.info/image_files/logos/90/1076.jpg",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "toyota",
        "30,234",
        "statistics",
        "toyota",
        "12,300",
        "map",
        "toyota",
        "1,233,500",
        "images",
        "toyota",
        "123,956",
        ],
        done:"Series",
        foto:["https://imgd.aeplcdn.com/642x336/n/cw/ec/139739/land-cruiser-exterior-right-front-three-quarter-2.jpeg?isig=0&q=80",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkk8MC_vPNmNQReIyHetUsew-3QtpVWmX1cJb0sEmMOWzyGwsivj3-LgDQdSOREYjS0uU&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSy3FHJRfvbfMH9B4qRk32zjKL53EtY3diigEZe1QKXTWpNRaNfhS-ERE_vdfY29NtChvc&usqp=CAU",
        "https://i.dailymail.co.uk/1s/2023/08/03/10/73918305-0-image-a-79_1691056791633.jpg",
        ],
        page:["EM90",
        "MPV 6 seats",
        "Electric",
        "EM30",
        "lux 5 seats",
        "Electric",
        "EX90",
        "SUV 7 seats",
        "Electric",
        "S60",
        "Sedan 5 seats",
        "Petrol Diesel",
        ],
        secret:["2021",
        "em 34",
        "123,000dollars",
        "dc",
        "2022",
        "45,000dollars",
        "suv500",
        "vol207",
        "2023",
        "20dw",
        "suv23",
        "76,000euro",
        "2024",
        "lux23",
        "340,000dollars",
        "dc39",
        ],

        images:"https://s.car.info/image_files/logos/90/1076.jpg",
title:"Toyota",
micro:"1936-",
imgs:"https://s.car.info/g/flags/svg/mini/jp.svg",
    },
    {
        id:4,
        first:"ford",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["USA",
        "1903",
        "23ds",
        ],
        fistly:"https://s.car.info/image_files/logos/90/1077.jpg",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "ford",
        "30,234",
        "statistics",
        "ford",
        "12,300",
        "map",
        "ford",
        "1,233,500",
        "images",
        "ford",
        "123,956",
        ],
        done:"Series",
      foto:[
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSreBBLdc0Qu5E-vYOeMijcHNnLpjlJQawT8wWf9mi6iw&s",
        "https://edgecast-img.yahoo.net/mysterio/api/745FBA6A1E78E32BED6F56490031567A2931D0F5E7A08143E6A3B804E522687C/autoblog/resizefill_w660_h372;quality_80;format_webp;cc_31536000;/https://s.aolcdn.com/commerce/autodata/images/USC50FOC123A021001.jpg",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRezONNT5UOAsBeiEyH55g2mFad54DRusbV76yUgCg0bRRSXNTqt3ze9-ZkuXqcmBOz84&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQU_ifOv7w7B8v9wyq11Q9IJvK4g5WYAs4zSzLmv8A4MUn4mZGUYsPxyY2Stb0i5ufKckg&usqp=CAU",
      ],
page:["EM90",
"MPV 6 seats",
"Electric",
"EM30",
"SUV 5 seats",
"Electric",
"EX90",
"SUV 7 seats",
"Electric",
"S60",
"Sedan 5 seats",
"Petrol Diesel",
],
secret:["2021",
"em 34",
"123,000dollars",
"dc",
"2022",
"45,000dollars",
"suv500",
"vol207",
"2023",
"20dw",
"suv23",
"76,000euro",
"2024",
"lux23",
"340,000dollars",
"dc39",
],

        images:"https://s.car.info/image_files/logos/90/1077.jpg",
title:"Ford",
micro:"1903-",
imgs:"https://s.car.info/g/flags/svg/mini/us.svg",
    },
    {
        id:5,
        first:"Mercades-Benz",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["germany",
        "1926",
        "maybach20",
        ],
        fistly:"https://s.car.info/image_files/logos/90/1078.jpg",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],
        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["class90",
    "MPV x6 seats",
    "petrol",
    "xM30",
    "SUV x5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "gelik 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],

        images:"https://s.car.info/image_files/logos/90/1078.jpg",
title:"Mercedes-Benz",
micro:"1926-",
imgs:"https://s.car.info/g/flags/svg/mini/de.svg",
    },
    {
        id:6,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],
        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],

        images:"https://s.car.info/image_files/logos/90/1184.jpg",
title:"BMW",
micro:"1927-",
imgs:"https://s.car.info/g/flags/svg/mini/de.svg",
    },
    {
        id:7,
        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],

        images:"https://s.car.info/image_files/logos/90/1084.jpg",
title:"KIA",
micro:"1986-",
imgs:"https://s.car.info/g/flags/svg/mini/kr.svg",
    },
    {
        id:8,
        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],

        images:"	https://s.car.info/image_files/logos/90/1103.jpg",
title:"Audi",
micro:"1965-",
imgs:"https://s.car.info/g/flags/svg/mini/de.svg",
    },
    {
        id:9,
        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],
        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],

        images:"https://s.car.info/image_files/logos/90/1090.jpg",
title:"Renault",
micro:"1898-",
imgs:"https://s.car.info/g/flags/svg/mini/fr.svg",
    },
    {
        id:10,
        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],

        images:"https://s.car.info/image_files/logos/90/1089.jpg",
title:"Peugeot",
micro:"1932-",
imgs:"https://s.car.info/g/flags/svg/mini/fr.svg",
    },
    {
        id:11,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"https://s.car.info/image_files/logos/90/1092.jpg",
title:"Skoda",
micro:"1934-",
imgs:"https://s.car.info/g/flags/svg/mini/cz.svg",
    },
    {
        id:12,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"https://s.car.info/image_files/logos/90/1091.jpg",
title:"Saab",
micro:"1950-2014",
imgs:"https://s.car.info/g/flags/svg/mini/se.svg",
    },
    {
        id:13,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"https://s.car.info/image_files/logos/90/1087.jpg",
title:"Nissan",
micro:"1951-",
imgs:"https://s.car.info/g/flags/svg/mini/jp.svg",
    },
    {
        id:14,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"https://s.car.info/image_files/logos/90/1088.jpg",
title:"Opel",
micro:"1924-",
imgs:"https://s.car.info/g/flags/svg/mini/de.svg",
    },
    {
        id:15,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"https://s.car.info/image_files/logos/90/1083.jpg",
title:"Hyundai",
micro:"1968-",
imgs:"https://s.car.info/g/flags/svg/mini/kr.svg",
    },
    {
        id:16,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"https://s.car.info/image_files/logos/90/1081.jpg",
title:"Citroen",
micro:"1919-",
imgs:"https://s.car.info/g/flags/svg/mini/fr.svg",
    },
    {
        id:17,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"https://s.car.info/image_files/logos/90/1086.jpg",
title:"Mazda",
micro:"1970-",
imgs:"https://s.car.info/g/flags/svg/mini/jp.svg",
    },
    {
        id:18,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"https://s.car.info/image_files/logos/90/1080.jpg",
title:"CHevrolet",
micro:"1912-",
imgs:"https://s.car.info/g/flags/svg/mini/us.svg",
    },
    {
        id:19,
        images:"	https://s.car.info/image_files/logos/90/1102.jpg",
title:"Subaru",
micro:"1984-",
imgs:"https://s.car.info/g/flags/svg/mini/jp.svg",
    },
    {
        id:20,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"https://s.car.info/image_files/logos/90/1085.jpg",
title:"Mitsubishi",
micro:"1969-",
imgs:"https://s.car.info/g/flags/svg/mini/jp.svg",
    },
    {
        id:21,


        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"	https://s.car.info/image_files/logos/90/1101.jpg",
title:"SEAT",
micro:"1963-",
imgs:"https://s.car.info/g/flags/svg/mini/es.svg",
    },
    {
        id:22,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"https://s.car.info/image_files/logos/90/1082.jpg",
title:"Honda",
micro:"1949-",
imgs:"https://s.car.info/g/flags/svg/mini/jp.svg",
    },
    {
        id:23,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"https://s.car.info/image_files/logos/90/1097.jpg",
title:"Fiat",
micro:"1919-",
imgs:"https://s.car.info/g/flags/svg/mini/it.svg",
    },
    {
        id:24,

        first:"",

        description:["Country of origin",
        "Production years",
        "Series",
        ],
        block:["",
        "19",
        "",
        ],
        fistly:"",
        secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
        third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
        fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
        fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
        fon:["Clasifieds",
        "",
        "30,234",
        "statistics",
        "",
        "12,300",
        "map",
        "",
        "1,233,500",
        "images",
        "",
        "123,956",
        ],

        done:"Series",
        foto:[
            "",
            "",
            "",
            "",
          ],
    page:["EM90",
    "MPV 6 seats",
    "Electric",
    "EM30",
    "SUV 5 seats",
    "Electric",
    "EX90",
    "SUV 7 seats",
    "Electric",
    "S60",
    "Sedan 5 seats",
    "Petrol Diesel",
    ],
    secret:["2021",
    "em 34",
    "123,000dollars",
    "dc",
    "2022",
    "45,000dollars",
    "suv500",
    "vol207",
    "2023",
    "20dw",
    "suv23",
    "76,000euro",
    "2024",
    "lux23",
    "340,000dollars",
    "dc39",
    ],
        images:"https://s.car.info/image_files/logos/90/821.jpg",
title:"Tesla",
micro:"2008-",
imgs:"https://s.car.info/g/flags/svg/mini/us.svg",
    },
    {
id:25,

first:"",

description:["Country of origin",
"Production years",
"Series",
],
block:["",
"19",
"",
],
fistly:"",
secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
fon:["Clasifieds",
"",
"30,234",
"statistics",
"",
"12,300",
"map",
"",
"1,233,500",
"images",
"",
"123,956",
],

done:"Series",
foto:[
    "",
    "",
    "",
    "",
  ],
page:["EM90",
"MPV 6 seats",
"Electric",
"EM30",
"SUV 5 seats",
"Electric",
"EX90",
"SUV 7 seats",
"Electric",
"S60",
"Sedan 5 seats",
"Petrol Diesel",
],
secret:["2021",
"em 34",
"123,000dollars",
"dc",
"2022",
"45,000dollars",
"suv500",
"vol207",
"2023",
"20dw",
"suv23",
"76,000euro",
"2024",
"lux23",
"340,000dollars",
"dc39",
],
images:"https://s.car.info/image_files/logos/90/458.jpg",
title:"Suzuki",
micro:"1969-",
imgs:"https://s.car.info/g/flags/svg/mini/jp.svg",
    },
    {
id:26,

first:"",

description:["Country of origin",
"Production years",
"Series",
],
block:["",
"19",
"",
],
fistly:"",
secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
fon:["Clasifieds",
"",
"30,234",
"statistics",
"",
"12,300",
"map",
"",
"1,233,500",
"images",
"",
"123,956",
],

done:"Series",
foto:[
    "",
    "",
    "",
    "",
  ],
page:["EM90",
"MPV 6 seats",
"Electric",
"EM30",
"SUV 5 seats",
"Electric",
"EX90",
"SUV 7 seats",
"Electric",
"S60",
"Sedan 5 seats",
"Petrol Diesel",
],
secret:["2021",
"em 34",
"123,000dollars",
"dc",
"2022",
"45,000dollars",
"suv500",
"vol207",
"2023",
"20dw",
"suv23",
"76,000euro",
"2024",
"lux23",
"340,000dollars",
"dc39",
],
images:"	https://s.car.info/image_files/logos/90/1100.jpg",
title:"Porsche",
micro:"1950-",
imgs:"https://s.car.info/g/flags/svg/mini/de.svg",
    },
    {
id:27,
first:"",

description:["Country of origin",
"Production years",
"Series",
],
block:["",
"19",
"",
],
fistly:"",
secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
fon:["Clasifieds",
"",
"30,234",
"statistics",
"",
"12,300",
"map",
"",
"1,233,500",
"images",
"",
"123,956",
],

done:"Series",
foto:[
    "",
    "",
    "",
    "",
  ],
page:["EM90",
"MPV 6 seats",
"Electric",
"EM30",
"SUV 5 seats",
"Electric",
"EX90",
"SUV 7 seats",
"Electric",
"S60",
"Sedan 5 seats",
"Petrol Diesel",
],
secret:["2021",
"em 34",
"123,000dollars",
"dc",
"2022",
"45,000dollars",
"suv500",
"vol207",
"2023",
"20dw",
"suv23",
"76,000euro",
"2024",
"lux23",
"340,000dollars",
"dc39",
],
images:"https://s.car.info/image_files/logos/90/58.jpg",
title:"MG",
micro:"1924-",
imgs:"https://s.car.info/g/flags/svg/mini/gb.svg",
    },
    {
id:28,

first:"",

description:["Country of origin",
"Production years",
"Series",
],
block:["",
"19",
"",
],
fistly:"",
secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
fon:["Clasifieds",
"",
"30,234",
"statistics",
"",
"12,300",
"map",
"",
"1,233,500",
"images",
"",
"123,956",
],

done:"Series",
foto:[
    "",
    "",
    "",
    "",
  ],
page:["EM90",
"MPV 6 seats",
"Electric",
"EM30",
"SUV 5 seats",
"Electric",
"EX90",
"SUV 7 seats",
"Electric",
"S60",
"Sedan 5 seats",
"Petrol Diesel",
],
secret:["2021",
"em 34",
"123,000dollars",
"dc",
"2022",
"45,000dollars",
"suv500",
"vol207",
"2023",
"20dw",
"suv23",
"76,000euro",
"2024",
"lux23",
"340,000dollars",
"dc39",
],
images:"https://s.car.info/image_files/logos/90/1075.jpg",
title:"Lexus",
micro:"1989-",
imgs:"https://s.car.info/g/flags/svg/mini/jp.svg",
    },
    {
id:29,

first:"",

description:["Country of origin",
"Production years",
"Series",
],
block:["",
"19",
"",
],
fistly:"",
secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
fon:["Clasifieds",
"",
"30,234",
"statistics",
"",
"12,300",
"map",
"",
"1,233,500",
"images",
"",
"123,956",
],

done:"Series",
foto:[
    "",
    "",
    "",
    "",
  ],
page:["EM90",
"MPV 6 seats",
"Electric",
"EM30",
"SUV 5 seats",
"Electric",
"EX90",
"SUV 7 seats",
"Electric",
"S60",
"Sedan 5 seats",
"Petrol Diesel",
],
secret:["2021",
"em 34",
"123,000dollars",
"dc",
"2022",
"45,000dollars",
"suv500",
"vol207",
"2023",
"20dw",
"suv23",
"76,000euro",
"2024",
"lux23",
"340,000dollars",
"dc39",
],
images:"https://s.car.info/image_files/logos/90/1098.jpg",
title:"Jeep",
micro:"1948-",
imgs:"https://s.car.info/g/flags/svg/mini/us.svg",
    },
    {
id:30,

first:"",

description:["Country of origin",
"Production years",
"Series",
],
block:["",
"19",
"",
],
fistly:"",
secondly:"https://s.car.info/g/illustrations/frontpage/classifieds.svg",
third:"https://s.car.info/g/illustrations/frontpage/stats.svg",
fourth:"https://s.car.info/g/illustrations/frontpage/map.svg",
fives:"https://s.car.info/g/illustrations/frontpage/camera.svg",
fon:["Clasifieds",
"",
"30,234",
"statistics",
"",
"12,300",
"map",
"",
"1,233,500",
"images",
"",
"123,956",
],

done:"Series",
foto:[
    "",
    "",
    "",
    "",
  ],
page:["EM90",
"MPV 6 seats",
"Electric",
"EM30",
"SUV 5 seats",
"Electric",
"EX90",
"SUV 7 seats",
"Electric",
"S60",
"Sedan 5 seats",
"Petrol Diesel",
],
secret:["2021",
"em 34",
"123,000dollars",
"dc",
"2022",
"45,000dollars",
"suv500",
"vol207",
"2023",
"20dw",
"suv23",
"76,000euro",
"2024",
"lux23",
"340,000dollars",
"dc39",
],
images:"https://s.car.info/image_files/logos/90/596.jpg",
title:"Land Rover",
micro:"1948-",
imgs:"https://s.car.info/g/flags/svg/mini/gb.svg",
    },
  
]

let show = document.querySelector(".show")
let close = document.querySelector(".close")
let container = document.querySelector(".container")

let first = document.querySelector(".first")
let firstly = document.querySelector(".firstly")
let midd = document.querySelector(".midd")
let midl = document.querySelector(".midl")
let midy = document.querySelector(".midy")

let erad = document.querySelector(".erad")
let eral = document.querySelector(".eral")
let eray = document.querySelector(".eray")
let secondly = document.querySelector(".secondly")
let bob = document.querySelector(".bob")
let six = document.querySelector(".six")
let sixl = document.querySelector(".sixl")
let third = document.querySelector(".third")
let boby = document.querySelector(".boby")
let sixy = document.querySelector(".sixy")
let sixd = document.querySelector(".sixd")
let fourth = document.querySelector(".fourth")
let bobb = document.querySelector(".bobb")
let sev = document.querySelector(".sev")
let sevy = document.querySelector(".sevy")

let fives = document.querySelector(".fives")
let bobth = document.querySelector(".bobth")
let sixth = document.querySelector(".sixth")
let sixthy = document.querySelector(".sixthy")
let done = document.querySelector(".done")
let photo_one = document.querySelector(".photo_one")
let one = document.querySelector(".one")
let two = document.querySelector(".two")
let three = document.querySelector(".three")
let hash = document.querySelector(".hash")
let yellow = document.querySelector(".yellow")
let yell = document.querySelector(".yell")
let yello = document.querySelector(".yello")
let photo_two = document.querySelector(".photo_two")
let oneth = document.querySelector(".oneth")
let twoth = document.querySelector(".twoth")
let threeth = document.querySelector(".threeth")
let hashy = document.querySelector(".hashy")
let yellow_two = document.querySelector(".yellow_two")
let yell_two = document.querySelector(".yell_two")
let yello_two = document.querySelector(".yello_two")
let photo_three = document.querySelector(".photo_three")
let one_three = document.querySelector(".one_three")
let two_three = document.querySelector(".two_three")
let three_th = document.querySelector(".three_th")
let hash_three = document.querySelector(".hash_three")
let yellow_three = document.querySelector(".yellow_three")
let yell_three = document.querySelector(".yell_three")
let yello_three = document.querySelector(".yello_three")
let photo_four = document.querySelector(".photo_four")
let one_four = document.querySelector(".one_four")
let two_four = document.querySelector(".two_four")
let three_four = document.querySelector(".three_four")
let hash_four = document.querySelector(".hash_four")
let yellow_four = document.querySelector(".yellow_four")
let yell_four = document.querySelector(".yell_four")
let yello_four = document.querySelector(".yello_four")
let text = document.querySelector(".text")
let popup = document.querySelector(".popup")


close.addEventListener('click', () => {
    container.style.transform = "translateY(-140%)"
})


let wrapper = document.querySelector('.wrapper')


function createCard(){
    data.map(item =>
{
    let card = document.createElement("div")
    card.classList.add('card')
    let img = document.createElement("img")
   img.setAttribute('src',item.images) 
   let title = document.createElement('p')
   title.innerHTML = item.title
   let micro = document.createElement('span')
   micro.innerHTML = item.micro
   let imgs = document.createElement('img')
   imgs.setAttribute('src',item.imgs)


   card.append(img)
   card.append(title)
   card.append(micro)
   card.append(imgs)

   wrapper.append(card)

   card.addEventListener('click',() => {

    container.style.transform = "translateY(0%)"

    first.innerHTML = item.first
  
          
    midd.innerHTML = item.description[0]
    midl.innerHTML = item.description[1]
    midy.innerHTML = item.description[2]
   

    firstly.setAttribute('src',item.firstly)
    erad.innerHTML = item.block[0]
    eral.innerHTML = item.block[1]
    eray.innerHTML = item.block[2]

    secondly.setAttribute('src',item.secondly)
    bob.innerHTML = item.fon[0]
    six.innerHTML = item.fon[1]
    sixl.innerHTML = item.fon[2]
    third.setAttribute('src',item.third)
    boby.innerHTML = item.fon[3]
    sixy.innerHTML = item.fon[4]
    sixd.innerHTML = item.fon[5]
    fourth.setAttribute('src',item.fourth)
    bobb.innerHTML = item.fon[6]
    sev.innerHTML = item.fon[7]
    sevy.innerHTML = item.fon[8]
    fives.setAttribute('src',item.fives)
    bobth.innerHTML = item.fon[9]
    sixth.innerHTML = item.fon[10]
    sixthy.innerHTML = item.fon[11]

    done.innerHTML = item.done
    photo_one.setAttribute('src',item.foto[0])
    one.innerHTML = item.page[0]
    two.innerHTML = item.page[1]
    three.innerHTML = item.page[2]
    hash.innerHTML = item.secret[0]
    yellow.innerHTML = item.secret[1]
    yell.innerHTML = item.secret[2]
    yello.innerHTML = item.secret[3]
    photo_two.setAttribute('src',item.foto[1])
    oneth.innerHTML = item.page[3]
    twoth.innerHTML = item.page[4]
    threeth.innerHTML = item.page[5]
    hashy.innerHTML = item.secret[4]
    yellow_two.innerHTML = item.secret[5]
    yell_two.innerHTML = item.secret[6]
    yello_two.innerHTML = item.secret[7]
    photo_three.setAttribute('src',item.foto[2])
    one_three.innerHTML = item.page[6]
    two_three.innerHTML = item.page[7]
    three_th.innerHTML = item.page[8]
    hash_three.innerHTML = item.secret[8]
    yellow_three.innerHTML = item.secret[9]
    yell_three.innerHTML = item.secret[10]
    yello_three.innerHTML = item.secret[11]
    photo_four.setAttribute('src',item.foto[3])
    one_four.innerHTML = item.page[9]
    two_four.innerHTML = item.page[10]
    three_four.innerHTML = item.page[11]
    hash_four.innerHTML = item.secret[12]
    yellow_four.innerHTML = item.secret[13]
    yell_four.innerHTML = item.secret[14]
    yello_four.innerHTML = item.secret[15]
    text.innerHTML = item.text
   
   


   }
   
   )

}
    )
}

createCard()
























